# Generated by Django 4.1.7 on 2023-03-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created_by',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='created_on',
            new_name='updated_on',
        ),
    ]
