# Generated by Django 4.1.7 on 2023-03-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0002_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expected_dep_time', models.DateTimeField()),
                ('expected_arval_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('end_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.end')),
                ('start_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TripSeatsInvolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seats.seattype')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
            options={
                'unique_together': {('seat_type', 'trip')},
            },
        ),
        migrations.CreateModel(
            name='TripSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chartseats')),
                ('trip_seats_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.tripseatsinvolved')),
            ],
        ),
        migrations.CreateModel(
            name='TripPricings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currency')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seats.seattype')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('Departure', 'Departure'), ('Arrival', 'Arrival')], max_length=255)),
                ('comments', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
            options={
                'unique_together': {('trip', 'state')},
            },
        ),
    ]
